(ns bible-plan.core)

(def bible
  #{{:name "Genesis" :chapters 50}
    {:name "Exodus" :chapters 40}
    {:name "Leviticus" :chapters 27}
    {:name "Numbers" :chapters 36}
    {:name "Deuteronomy" :chapters 34}
    {:name "Joshua" :chapters 24}
    {:name "Judges" :chapters 21}
    {:name "Ruth" :chapters 4}
    {:name "1 Samuel" :chapters 31}
    {:name "2 Samuel" :chapters 24}
    {:name "1 Kings" :chapters 22}
    {:name "2 Kings" :chapters 25}
    {:name "1 Chronicles" :chapters 29}
    {:name "2 Chronicles" :chapters 36}
    {:name "Ezra" :chapters 10}
    {:name "Nehemiah" :chapters 13}
    {:name "Esther" :chapters 10}
    {:name "Job" :chapters 42}
    {:name "Psalms" :chapters 150}
    {:name "Proverbs" :chapters 31}
    {:name "Ecclesiastes" :chapters 12}
    {:name "Song of Songs" :chapters 8}
    {:name "Isaiah" :chapters 66}
    {:name "Jeremiah" :chapters 52}
    {:name "Lamentations" :chapters 5}
    {:name "Ezekiel" :chapters 48}
    {:name "Daniel" :chapters 14}
    {:name "Hosea" :chapters 14}
    {:name "Joel" :chapters 4}
    {:name "Amos" :chapters 9}
    {:name "Obadiah" :chapters 1}
    {:name "Jonah" :chapters 4}
    {:name "Micah" :chapters 7}
    {:name "Nahum" :chapters 3}
    {:name "Habakkuk" :chapters 3}
    {:name "Zephaniah" :chapters 3}
    {:name "Haggai" :chapters 2}
    {:name "Zechariah" :chapters 14}
    {:name "Malachi" :chapters 3}
    {:name "Matthew" :chapters 28}
    {:name "Mark" :chapters 16}
    {:name "Luke" :chapters 24}
    {:name "John" :chapters 21}
    {:name "Acts" :chapters 28N}
    {:name "Romans" :chapters 16}
    {:name "1 Corinthians" :chapters 16}
    {:name "2 Corinthians" :chapters 13}
    {:name "Galatians" :chapters 6}
    {:name "Ephesians" :chapters 6}
    {:name "Philippians" :chapters 4}
    {:name "Colossians" :chapters 4}
    {:name "1 Thessalonians" :chapters 5}
    {:name "2 Thessalonians" :chapters 3}
    {:name "1 Timothy" :chapters 6}
    {:name "2 Timothy" :chapters 4}
    {:name "Titus" :chapters 3}
    {:name "Philemon" :chapters 1}
    {:name "Hebrews" :chapters 13}
    {:name "James" :chapters 5}
    {:name "1 Peter" :chapters 5}
    {:name "2 Peter" :chapters 3}
    {:name "1 John" :chapters 5}
    {:name "2 John" :chapters 1}
    {:name "3 John" :chapters 1}
    {:name "Jude" :chapters 1}
    {:name "Revelation" :chapters 22}})

(def mcheyne
  [[{:start {:book "Genesis" :chapter 1}} {:start {:book "Matthew" :chapter 1}} {:start {:book "Ezra" :chapter 1}} {:start {:book "Acts" :chapter 1}}]
   [{:start {:book "Genesis" :chapter 2}} {:start {:book "Matthew" :chapter 2}} {:start {:book "Ezra" :chapter 2}} {:start {:book "Acts" :chapter 2}}]
   [{:start {:book "Genesis" :chapter 3}} {:start {:book "Matthew" :chapter 3}} {:start {:book "Ezra" :chapter 3}} {:start {:book "Acts" :chapter 3}}]
   [{:start {:book "Genesis" :chapter 4}} {:start {:book "Matthew" :chapter 4}} {:start {:book "Ezra" :chapter 4}} {:start {:book "Acts" :chapter 4}}]
   [{:start {:book "Genesis" :chapter 5}} {:start {:book "Matthew" :chapter 5}} {:start {:book "Ezra" :chapter 5}} {:start {:book "Acts" :chapter 5}}]
   [{:start {:book "Genesis" :chapter 6}} {:start {:book "Matthew" :chapter 6}} {:start {:book "Ezra" :chapter 6}} {:start {:book "Acts" :chapter 6}}]
   [{:start {:book "Genesis" :chapter 7}} {:start {:book "Matthew" :chapter 7}} {:start {:book "Ezra" :chapter 7}} {:start {:book "Acts" :chapter 7}}]
   [{:start {:book "Genesis" :chapter 8}} {:start {:book "Matthew" :chapter 8}} {:start {:book "Ezra" :chapter 8}} {:start {:book "Acts" :chapter 8}}]
   [{:start {:book "Genesis" :chapter 9} :end {:book "Genesis" :chapter 10}} {:start {:book "Matthew" :chapter 9}} {:start {:book "Ezra" :chapter 9}} {:start {:book "Acts" :chapter 9}}]
   [{:start {:book "Genesis" :chapter 11}} {:start {:book "Matthew" :chapter 10}} {:start {:book "Ezra" :chapter 10}} {:start {:book "Acts" :chapter 10}}]
   [{:start {:book "Genesis" :chapter 12}} {:start {:book "Matthew" :chapter 11}} {:start {:book "Nehemiah" :chapter 1}} {:start {:book "Acts" :chapter 11}}]
   [{:start {:book "Genesis" :chapter 13}} {:start {:book "Matthew" :chapter 12}} {:start {:book "Nehemiah" :chapter 2}} {:start {:book "Acts" :chapter 12}}]
   [{:start {:book "Genesis" :chapter 14}} {:start {:book "Matthew" :chapter 13}} {:start {:book "Nehemiah" :chapter 3}} {:start {:book "Acts" :chapter 13}}]
   [{:start {:book "Genesis" :chapter 15}} {:start {:book "Matthew" :chapter 14}} {:start {:book "Nehemiah" :chapter 4}} {:start {:book "Acts" :chapter 14}}]
   [{:start {:book "Genesis" :chapter 16}} {:start {:book "Matthew" :chapter 15}} {:start {:book "Nehemiah" :chapter 5}} {:start {:book "Acts" :chapter 15}}]
   [{:start {:book "Genesis" :chapter 17}} {:start {:book "Matthew" :chapter 16}} {:start {:book "Nehemiah" :chapter 6}} {:start {:book "Acts" :chapter 16}}]
   [{:start {:book "Genesis" :chapter 18}} {:start {:book "Matthew" :chapter 17}} {:start {:book "Nehemiah" :chapter 7}} {:start {:book "Acts" :chapter 17}}]
   [{:start {:book "Genesis" :chapter 19}} {:start {:book "Matthew" :chapter 18}} {:start {:book "Nehemiah" :chapter 8}} {:start {:book "Acts" :chapter 18}}]
   [{:start {:book "Genesis" :chapter 20}} {:start {:book "Matthew" :chapter 19}} {:start {:book "Nehemiah" :chapter 9}} {:start {:book "Acts" :chapter 19}}]
   [{:start {:book "Genesis" :chapter 21}} {:start {:book "Matthew" :chapter 20}} {:start {:book "Nehemiah" :chapter 10}} {:start {:book "Acts" :chapter 20}}]
   [{:start {:book "Genesis" :chapter 22}} {:start {:book "Matthew" :chapter 21}} {:start {:book "Nehemiah" :chapter 11}} {:start {:book "Acts" :chapter 21}}]
   [{:start {:book "Genesis" :chapter 23}} {:start {:book "Matthew" :chapter 22}} {:start {:book "Nehemiah" :chapter 12}} {:start {:book "Acts" :chapter 22}}]
   [{:start {:book "Genesis" :chapter 24}} {:start {:book "Matthew" :chapter 23}} {:start {:book "Nehemiah" :chapter 13}} {:start {:book "Acts" :chapter 23}}]
   [{:start {:book "Genesis" :chapter 25}} {:start {:book "Matthew" :chapter 24}} {:start {:book "Esther" :chapter 1}} {:start {:book "Acts" :chapter 24}}]
   [{:start {:book "Genesis" :chapter 26}} {:start {:book "Matthew" :chapter 25}} {:start {:book "Esther" :chapter 2}} {:start {:book "Acts" :chapter 25}}]
   [{:start {:book "Genesis" :chapter 27}} {:start {:book "Matthew" :chapter 26}} {:start {:book "Esther" :chapter 3}} {:start {:book "Acts" :chapter 26}}]
   [{:start {:book "Genesis" :chapter 28}} {:start {:book "Matthew" :chapter 27}} {:start {:book "Esther" :chapter 4}} {:start {:book "Acts" :chapter 27}}]
   [{:start {:book "Genesis" :chapter 29}} {:start {:book "Matthew" :chapter 28}} {:start {:book "Esther" :chapter 5}} {:start {:book "Acts" :chapter 28}}]
   [{:start {:book "Genesis" :chapter 30}} {:start {:book "Mark" :chapter 1}} {:start {:book "Esther" :chapter 6}} {:start {:book "Romans" :chapter 1}}]
   [{:start {:book "Genesis" :chapter 31}} {:start {:book "Mark" :chapter 2}} {:start {:book "Esther" :chapter 7}} {:start {:book "Romans" :chapter 2}}]
   [{:start {:book "Genesis" :chapter 32}} {:start {:book "Mark" :chapter 3}} {:start {:book "Esther" :chapter 8}} {:start {:book "Romans" :chapter 3}}]
   [{:start {:book "Genesis" :chapter 33}} {:start {:book "Mark" :chapter 4}} {:start {:book "Esther" :chapter 9} :end {:book "Esther" :chapter 10}} {:start {:book "Romans" :chapter 4}}]
   [{:start {:book "Genesis" :chapter 34}} {:start {:book "Mark" :chapter 5}} {:start {:book "Job" :chapter 1}} {:start {:book "Romans" :chapter 5}}]
   [{:start {:book "Genesis" :chapter 35} :end {:book "Genesis" :chapter 36}} {:start {:book "Mark" :chapter 6}} {:start {:book "Job" :chapter 2}} {:start {:book "Romans" :chapter 6}}]
   [{:start {:book "Genesis" :chapter 37}} {:start {:book "Mark" :chapter 7}} {:start {:book "Job" :chapter 3}} {:start {:book "Romans" :chapter 7}}]
   [{:start {:book "Genesis" :chapter 38}} {:start {:book "Mark" :chapter 8}} {:start {:book "Job" :chapter 4}} {:start {:book "Romans" :chapter 8}}]
   [{:start {:book "Genesis" :chapter 39}} {:start {:book "Mark" :chapter 9}} {:start {:book "Job" :chapter 5}} {:start {:book "Romans" :chapter 9}}]
   [{:start {:book "Genesis" :chapter 40}} {:start {:book "Mark" :chapter 10}} {:start {:book "Job" :chapter 6}} {:start {:book "Romans" :chapter 10}}]
   [{:start {:book "Genesis" :chapter 41}} {:start {:book "Mark" :chapter 11}} {:start {:book "Job" :chapter 7}} {:start {:book "Romans" :chapter 11}}]
   [{:start {:book "Genesis" :chapter 42}} {:start {:book "Mark" :chapter 12}} {:start {:book "Job" :chapter 8}} {:start {:book "Romans" :chapter 12}}]
   [{:start {:book "Genesis" :chapter 43}} {:start {:book "Mark" :chapter 13}} {:start {:book "Job" :chapter 9}} {:start {:book "Romans" :chapter 13}}]
   [{:start {:book "Genesis" :chapter 44}} {:start {:book "Mark" :chapter 14}} {:start {:book "Job" :chapter 10}} {:start {:book "Romans" :chapter 14}}]
   [{:start {:book "Genesis" :chapter 45}} {:start {:book "Mark" :chapter 15}} {:start {:book "Job" :chapter 11}} {:start {:book "Romans" :chapter 15}}]
   [{:start {:book "Genesis" :chapter 46}} {:start {:book "Mark" :chapter 16}} {:start {:book "Job" :chapter 12}} {:start {:book "Romans" :chapter 16}}]
   [{:start {:book "Genesis" :chapter 47}} {:start {:verse 1 :book "Luke" :chapter 1} :end {:verse 38 :book "Luke" :chapter 1}} {:start {:book "Job" :chapter 13}} {:start {:book "1 Corinthians" :chapter 1}}]
   [{:start {:book "Genesis" :chapter 48}} {:start {:verse 39 :book "Luke" :chapter 1}} {:start {:book "Job" :chapter 14}} {:start {:book "1 Corinthians" :chapter 2}}]
   [{:start {:book "Genesis" :chapter 49}} {:start {:book "Luke" :chapter 2}} {:start {:book "Job" :chapter 15}} {:start {:book "1 Corinthians" :chapter 3}}]
   [{:start {:book "Genesis" :chapter 50}} {:start {:book "Luke" :chapter 3}} {:start {:book "Job" :chapter 16} :end {:book "Job" :chapter 17}} {:start {:book "1 Corinthians" :chapter 4}}]
   [{:start {:book "Exodus" :chapter 1}} {:start {:book "Luke" :chapter 4}} {:start {:book "Job" :chapter 18}} {:start {:book "1 Corinthians" :chapter 5}}]
   [{:start {:book "Exodus" :chapter 2}} {:start {:book "Luke" :chapter 5}} {:start {:book "Job" :chapter 19}} {:start {:book "1 Corinthians" :chapter 6}}]
   [{:start {:book "Exodus" :chapter 3}} {:start {:book "Luke" :chapter 6}} {:start {:book "Job" :chapter 20}} {:start {:book "1 Corinthians" :chapter 7}}]
   [{:start {:book "Exodus" :chapter 4}} {:start {:book "Luke" :chapter 7}} {:start {:book "Job" :chapter 21}} {:start {:book "1 Corinthians" :chapter 8}}]
   [{:start {:book "Exodus" :chapter 5}} {:start {:book "Luke" :chapter 8}} {:start {:book "Job" :chapter 22}} {:start {:book "1 Corinthians" :chapter 9}}]
   [{:start {:book "Exodus" :chapter 6}} {:start {:book "Luke" :chapter 9}} {:start {:book "Job" :chapter 23}} {:start {:book "1 Corinthians" :chapter 10}}]
   [{:start {:book "Exodus" :chapter 7}} {:start {:book "Luke" :chapter 10}} {:start {:book "Job" :chapter 24}} {:start {:book "1 Corinthians" :chapter 11}}]
   [{:start {:book "Exodus" :chapter 8}} {:start {:book "Luke" :chapter 11}} {:start {:book "Job" :chapter 25} :end {:book "Job" :chapter 26}} {:start {:book "1 Corinthians" :chapter 12}}]
   [{:start {:book "Exodus" :chapter 9}} {:start {:book "Luke" :chapter 12}} {:start {:book "Job" :chapter 27}} {:start {:book "1 Corinthians" :chapter 13}}]
   [{:start {:book "Exodus" :chapter 10}} {:start {:book "Luke" :chapter 13}} {:start {:book "Job" :chapter 28}} {:start {:book "1 Corinthians" :chapter 14}}]
   [{:start {:book "Exodus" :chapter 11} :end {:verse 21 :book "Exodus" :chapter 12}} {:start {:book "Luke" :chapter 14}} {:start {:book "Job" :chapter 29}} {:start {:book "1 Corinthians" :chapter 15}}]
   [{:start {:verse 22 :book "Exodus" :chapter 12}} {:start {:book "Luke" :chapter 15}} {:start {:book "Job" :chapter 30}} {:start {:book "1 Corinthians" :chapter 16}}]
   [{:start {:book "Exodus" :chapter 13}} {:start {:book "Luke" :chapter 16}} {:start {:book "Job" :chapter 31}} {:start {:book "2 Corinthians" :chapter 1}}]
   [{:start {:book "Exodus" :chapter 14}} {:start {:book "Luke" :chapter 17}} {:start {:book "Job" :chapter 32}} {:start {:book "2 Corinthians" :chapter 2}}]
   [{:start {:book "Exodus" :chapter 15}} {:start {:book "Luke" :chapter 18}} {:start {:book "Job" :chapter 33}} {:start {:book "2 Corinthians" :chapter 3}}]
   [{:start {:book "Exodus" :chapter 16}} {:start {:book "Luke" :chapter 19}} {:start {:book "Job" :chapter 34}} {:start {:book "2 Corinthians" :chapter 4}}]
   [{:start {:book "Exodus" :chapter 17}} {:start {:book "Luke" :chapter 20}} {:start {:book "Job" :chapter 35}} {:start {:book "2 Corinthians" :chapter 5}}]
   [{:start {:book "Exodus" :chapter 18}} {:start {:book "Luke" :chapter 21}} {:start {:book "Job" :chapter 36}} {:start {:book "2 Corinthians" :chapter 6}}]
   [{:start {:book "Exodus" :chapter 19}} {:start {:book "Luke" :chapter 22}} {:start {:book "Job" :chapter 37}} {:start {:book "2 Corinthians" :chapter 7}}]
   [{:start {:book "Exodus" :chapter 20}} {:start {:book "Luke" :chapter 23}} {:start {:book "Job" :chapter 38}} {:start {:book "2 Corinthians" :chapter 8}}]
   [{:start {:book "Exodus" :chapter 21}} {:start {:book "Luke" :chapter 24}} {:start {:book "Job" :chapter 39}} {:start {:book "2 Corinthians" :chapter 9}}]
   [{:start {:book "Exodus" :chapter 22}} {:start {:book "John" :chapter 1}} {:start {:book "Job" :chapter 40}} {:start {:book "2 Corinthians" :chapter 10}}]
   [{:start {:book "Exodus" :chapter 23}} {:start {:book "John" :chapter 2}} {:start {:book "Job" :chapter 41}} {:start {:book "2 Corinthians" :chapter 11}}]
   [{:start {:book "Exodus" :chapter 24}} {:start {:book "John" :chapter 3}} {:start {:book "Job" :chapter 42}} {:start {:book "2 Corinthians" :chapter 12}}]
   [{:start {:book "Exodus" :chapter 25}} {:start {:book "John" :chapter 4}} {:start {:book "Proverbs" :chapter 1}} {:start {:book "2 Corinthians" :chapter 13}}]
   [{:start {:book "Exodus" :chapter 26}} {:start {:book "John" :chapter 5}} {:start {:book "Proverbs" :chapter 2}} {:start {:book "Galatians" :chapter 1}}]
   [{:start {:book "Exodus" :chapter 27}} {:start {:book "John" :chapter 6}} {:start {:book "Proverbs" :chapter 3}} {:start {:book "Galatians" :chapter 2}}]
   [{:start {:book "Exodus" :chapter 28}} {:start {:book "John" :chapter 7}} {:start {:book "Proverbs" :chapter 4}} {:start {:book "Galatians" :chapter 3}}]
   [{:start {:book "Exodus" :chapter 29}} {:start {:book "John" :chapter 8}} {:start {:book "Proverbs" :chapter 5}} {:start {:book "Galatians" :chapter 4}}]
   [{:start {:book "Exodus" :chapter 30}} {:start {:book "John" :chapter 9}} {:start {:book "Proverbs" :chapter 6}} {:start {:book "Galatians" :chapter 5}}]
   [{:start {:book "Exodus" :chapter 31}} {:start {:book "John" :chapter 10}} {:start {:book "Proverbs" :chapter 7}} {:start {:book "Galatians" :chapter 6}}]
   [{:start {:book "Exodus" :chapter 32}} {:start {:book "John" :chapter 11}} {:start {:book "Proverbs" :chapter 8}} {:start {:book "Ephesians" :chapter 1}}]
   [{:start {:book "Exodus" :chapter 33}} {:start {:book "John" :chapter 12}} {:start {:book "Proverbs" :chapter 9}} {:start {:book "Ephesians" :chapter 2}}]
   [{:start {:book "Exodus" :chapter 34}} {:start {:book "John" :chapter 13}} {:start {:book "Proverbs" :chapter 10}} {:start {:book "Ephesians" :chapter 3}}]
   [{:start {:book "Exodus" :chapter 35}} {:start {:book "John" :chapter 14}} {:start {:book "Proverbs" :chapter 11}} {:start {:book "Ephesians" :chapter 4}}]
   [{:start {:book "Exodus" :chapter 36}} {:start {:book "John" :chapter 15}} {:start {:book "Proverbs" :chapter 12}} {:start {:book "Ephesians" :chapter 5}}]
   [{:start {:book "Exodus" :chapter 37}} {:start {:book "John" :chapter 16}} {:start {:book "Proverbs" :chapter 13}} {:start {:book "Ephesians" :chapter 6}}]
   [{:start {:book "Exodus" :chapter 38}} {:start {:book "John" :chapter 17}} {:start {:book "Proverbs" :chapter 14}} {:start {:book "Philippians" :chapter 1}}]
   [{:start {:book "Exodus" :chapter 39}} {:start {:book "John" :chapter 18}} {:start {:book "Proverbs" :chapter 15}} {:start {:book "Philippians" :chapter 2}}]
   [{:start {:book "Exodus" :chapter 40}} {:start {:book "John" :chapter 19}} {:start {:book "Proverbs" :chapter 16}} {:start {:book "Philippians" :chapter 3}}]
   [{:start {:book "Leviticus" :chapter 1}} {:start {:book "John" :chapter 20}} {:start {:book "Proverbs" :chapter 17}} {:start {:book "Philippians" :chapter 4}}]
   [{:start {:book "Leviticus" :chapter 2} :end {:book "Leviticus" :chapter 3}} {:start {:book "John" :chapter 21}} {:start {:book "Proverbs" :chapter 18}} {:start {:book "Colossians" :chapter 1}}]
   [{:start {:book "Leviticus" :chapter 4}} {:start {:book "Psalms" :chapter 1} :end {:book "Psalms" :chapter 2}} {:start {:book "Proverbs" :chapter 19}} {:start {:book "Colossians" :chapter 2}}]
   [{:start {:book "Leviticus" :chapter 5}} {:start {:book "Psalms" :chapter 3} :end {:book "Psalms" :chapter 4}} {:start {:book "Proverbs" :chapter 20}} {:start {:book "Colossians" :chapter 3}}]
   [{:start {:book "Leviticus" :chapter 6}} {:start {:book "Psalms" :chapter 5} :end {:book "Psalms" :chapter 6}} {:start {:book "Proverbs" :chapter 21}} {:start {:book "Colossians" :chapter 4}}]
   [{:start {:book "Leviticus" :chapter 7}} {:start {:book "Psalms" :chapter 7} :end {:book "Psalms" :chapter 8}} {:start {:book "Proverbs" :chapter 22}} {:start {:book "1 Thessalonians" :chapter 1}}]
   [{:start {:book "Leviticus" :chapter 8}} {:start {:book "Psalms" :chapter 9}} {:start {:book "Proverbs" :chapter 23}} {:start {:book "1 Thessalonians" :chapter 2}}]
   [{:start {:book "Leviticus" :chapter 9}} {:start {:book "Psalms" :chapter 10}} {:start {:book "Proverbs" :chapter 24}} {:start {:book "1 Thessalonians" :chapter 3}}]
   [{:start {:book "Leviticus" :chapter 10}} {:start {:book "Psalms" :chapter 11} :end {:book "Psalms" :chapter 12}} {:start {:book "Proverbs" :chapter 25}} {:start {:book "1 Thessalonians" :chapter 4}}]
   [{:start {:book "Leviticus" :chapter 11} :end {:book "Leviticus" :chapter 12}} {:start {:book "Psalms" :chapter 13} :end {:book "Psalms" :chapter 14}} {:start {:book "Proverbs" :chapter 26}} {:start {:book "1 Thessalonians" :chapter 5}}]
   [{:start {:book "Leviticus" :chapter 13}} {:start {:book "Psalms" :chapter 15} :end {:book "Psalms" :chapter 16}} {:start {:book "Proverbs" :chapter 27}} {:start {:book "2 Thessalonians" :chapter 1}}]
   [{:start {:book "Leviticus" :chapter 14}} {:start {:book "Psalms" :chapter 17}} {:start {:book "Proverbs" :chapter 28}} {:start {:book "2 Thessalonians" :chapter 2}}]
   [{:start {:book "Leviticus" :chapter 15}} {:start {:book "Psalms" :chapter 18}} {:start {:book "Proverbs" :chapter 29}} {:start {:book "2 Thessalonians" :chapter 3}}]
   [{:start {:book "Leviticus" :chapter 16}} {:start {:book "Psalms" :chapter 19}} {:start {:book "Proverbs" :chapter 30}} {:start {:book "1 Timothy" :chapter 1}}]
   [{:start {:book "Leviticus" :chapter 17}} {:start {:book "Psalms" :chapter 20} :end {:book "Psalms" :chapter 21}} {:start {:book "Proverbs" :chapter 31}} {:start {:book "1 Timothy" :chapter 2}}]
   [{:start {:book "Leviticus" :chapter 18}} {:start {:book "Psalms" :chapter 22}} {:start {:book "Ecclesiastes" :chapter 1}} {:start {:book "1 Timothy" :chapter 3}}]
   [{:start {:book "Leviticus" :chapter 19}} {:start {:book "Psalms" :chapter 23} :end {:book "Psalms" :chapter 24}} {:start {:book "Ecclesiastes" :chapter 2}} {:start {:book "1 Timothy" :chapter 4}}]
   [{:start {:book "Leviticus" :chapter 20}} {:start {:book "Psalms" :chapter 25}} {:start {:book "Ecclesiastes" :chapter 3}} {:start {:book "1 Timothy" :chapter 5}}]
   [{:start {:book "Leviticus" :chapter 21}} {:start {:book "Psalms" :chapter 26} :end {:book "Psalms" :chapter 27}} {:start {:book "Ecclesiastes" :chapter 4}} {:start {:book "1 Timothy" :chapter 6}}]
   [{:start {:book "Leviticus" :chapter 22}} {:start {:book "Psalms" :chapter 28} :end {:book "Psalms" :chapter 29}} {:start {:book "Ecclesiastes" :chapter 5}} {:start {:book "2 Timothy" :chapter 1}}]
   [{:start {:book "Leviticus" :chapter 23}} {:start {:book "Psalms" :chapter 30}} {:start {:book "Ecclesiastes" :chapter 6}} {:start {:book "2 Timothy" :chapter 2}}]
   [{:start {:book "Leviticus" :chapter 24}} {:start {:book "Psalms" :chapter 31}} {:start {:book "Ecclesiastes" :chapter 7}} {:start {:book "2 Timothy" :chapter 3}}]
   [{:start {:book "Leviticus" :chapter 25}} {:start {:book "Psalms" :chapter 32}} {:start {:book "Ecclesiastes" :chapter 8}} {:start {:book "2 Timothy" :chapter 4}}]
   [{:start {:book "Leviticus" :chapter 26}} {:start {:book "Psalms" :chapter 33}} {:start {:book "Ecclesiastes" :chapter 9}} {:start {:book "Titus" :chapter 1}}]
   [{:start {:book "Leviticus" :chapter 27}} {:start {:book "Psalms" :chapter 34}} {:start {:book "Ecclesiastes" :chapter 10}} {:start {:book "Titus" :chapter 2}}]
   [{:start {:book "Numbers" :chapter 1}} {:start {:book "Psalms" :chapter 35}} {:start {:book "Ecclesiastes" :chapter 11}} {:start {:book "Titus" :chapter 3}}]
   [{:start {:book "Numbers" :chapter 2}} {:start {:book "Psalms" :chapter 36}} {:start {:book "Ecclesiastes" :chapter 12}} {:start {:book "Philemon" :chapter 1}}]
   [{:start {:book "Numbers" :chapter 3}} {:start {:book "Psalms" :chapter 37}} {:start {:book "Song of Songs" :chapter 1}} {:start {:book "Hebrews" :chapter 1}}]
   [{:start {:book "Numbers" :chapter 4}} {:start {:book "Psalms" :chapter 38}} {:start {:book "Song of Songs" :chapter 2}} {:start {:book "Hebrews" :chapter 2}}]
   [{:start {:book "Numbers" :chapter 5}} {:start {:book "Psalms" :chapter 39}} {:start {:book "Song of Songs" :chapter 3}} {:start {:book "Hebrews" :chapter 3}}]
   [{:start {:book "Numbers" :chapter 6}} {:start {:book "Psalms" :chapter 40} :end {:book "Psalms" :chapter 41}} {:start {:book "Song of Songs" :chapter 4}} {:start {:book "Hebrews" :chapter 4}}]
   [{:start {:book "Numbers" :chapter 7}} {:start {:book "Psalms" :chapter 42} :end {:book "Psalms" :chapter 43}} {:start {:book "Song of Songs" :chapter 5}} {:start {:book "Hebrews" :chapter 5}}]
   [{:start {:book "Numbers" :chapter 8}} {:start {:book "Psalms" :chapter 44}} {:start {:book "Song of Songs" :chapter 6}} {:start {:book "Hebrews" :chapter 6}}]
   [{:start {:book "Numbers" :chapter 9}} {:start {:book "Psalms" :chapter 45}} {:start {:book "Song of Songs" :chapter 7}} {:start {:book "Hebrews" :chapter 7}}]
   [{:start {:book "Numbers" :chapter 10}} {:start {:book "Psalms" :chapter 46} :end {:book "Psalms" :chapter 47}} {:start {:book "Song of Songs" :chapter 8}} {:start {:book "Hebrews" :chapter 8}}]
   [{:start {:book "Numbers" :chapter 11}} {:start {:book "Psalms" :chapter 48}} {:start {:book "Isaiah" :chapter 1}} {:start {:book "Hebrews" :chapter 9}}]
   [{:start {:book "Numbers" :chapter 12} :end {:book "Numbers" :chapter 13}} {:start {:book "Psalms" :chapter 49}} {:start {:book "Isaiah" :chapter 2}} {:start {:book "Hebrews" :chapter 10}}]
   [{:start {:book "Numbers" :chapter 14}} {:start {:book "Psalms" :chapter 50}} {:start {:book "Isaiah" :chapter 3} :end {:book "Isaiah" :chapter 4}} {:start {:book "Hebrews" :chapter 11}}]
   [{:start {:book "Numbers" :chapter 15}} {:start {:book "Psalms" :chapter 51}} {:start {:book "Isaiah" :chapter 5}} {:start {:book "Hebrews" :chapter 12}}]
   [{:start {:book "Numbers" :chapter 16}} {:start {:book "Psalms" :chapter 52} :end {:book "Psalms" :chapter 54}} {:start {:book "Isaiah" :chapter 6}} {:start {:book "Hebrews" :chapter 13}}]
   [{:start {:book "Numbers" :chapter 17} :end {:book "Numbers" :chapter 18}} {:start {:book "Psalms" :chapter 55}} {:start {:book "Isaiah" :chapter 7}} {:start {:book "James" :chapter 1}}]
   [{:start {:book "Numbers" :chapter 19}} {:start {:book "Psalms" :chapter 56} :end {:book "Psalms" :chapter 57}} {:start {:book "Isaiah" :chapter 8} :end {:verse 7 :book "Isaiah" :chapter 9}} {:start {:book "James" :chapter 2}}]
   [{:start {:book "Numbers" :chapter 20}} {:start {:book "Psalms" :chapter 58} :end {:book "Psalms" :chapter 59}} {:start {:verse 8 :book "Isaiah" :chapter 9} :end {:verse 4 :book "Isaiah" :chapter 10}} {:start {:book "James" :chapter 3}}]
   [{:start {:book "Numbers" :chapter 21}} {:start {:book "Psalms" :chapter 60} :end {:book "Psalms" :chapter 61}} {:start {:verse 5 :book "Isaiah" :chapter 10}} {:start {:book "James" :chapter 4}}]
   [{:start {:book "Numbers" :chapter 22}} {:start {:book "Psalms" :chapter 62} :end {:book "Psalms" :chapter 63}} {:start {:book "Isaiah" :chapter 11} :end {:book "Isaiah" :chapter 12}} {:start {:book "James" :chapter 5}}]
   [{:start {:book "Numbers" :chapter 23}} {:start {:book "Psalms" :chapter 64} :end {:book "Psalms" :chapter 65}} {:start {:book "Isaiah" :chapter 13}} {:start {:book "1 Peter" :chapter 1}}]
   [{:start {:book "Numbers" :chapter 24}} {:start {:book "Psalms" :chapter 66} :end {:book "Psalms" :chapter 67}} {:start {:book "Isaiah" :chapter 14}} {:start {:book "1 Peter" :chapter 2}}]
   [{:start {:book "Numbers" :chapter 25}} {:start {:book "Psalms" :chapter 68}} {:start {:book "Isaiah" :chapter 15}} {:start {:book "1 Peter" :chapter 3}}]
   [{:start {:book "Numbers" :chapter 26}} {:start {:book "Psalms" :chapter 69}} {:start {:book "Isaiah" :chapter 16}} {:start {:book "1 Peter" :chapter 4}}]
   [{:start {:book "Numbers" :chapter 27}} {:start {:book "Psalms" :chapter 70} :end {:book "Psalms" :chapter 71}} {:start {:book "Isaiah" :chapter 17} :end {:book "Isaiah" :chapter 18}} {:start {:book "1 Peter" :chapter 5}}]
   [{:start {:book "Numbers" :chapter 28}} {:start {:book "Psalms" :chapter 72}} {:start {:book "Isaiah" :chapter 19} :end {:book "Isaiah" :chapter 20}} {:start {:book "2 Peter" :chapter 1}}]
   [{:start {:book "Numbers" :chapter 29}} {:start {:book "Psalms" :chapter 73}} {:start {:book "Isaiah" :chapter 21}} {:start {:book "2 Peter" :chapter 2}}]
   [{:start {:book "Numbers" :chapter 30}} {:start {:book "Psalms" :chapter 74}} {:start {:book "Isaiah" :chapter 22}} {:start {:book "2 Peter" :chapter 3}}]
   [{:start {:book "Numbers" :chapter 31}} {:start {:book "Psalms" :chapter 75} :end {:book "Psalms" :chapter 76}} {:start {:book "Isaiah" :chapter 23}} {:start {:book "1 John" :chapter 1}}]
   [{:start {:book "Numbers" :chapter 32}} {:start {:book "Psalms" :chapter 77}} {:start {:book "Isaiah" :chapter 24}} {:start {:book "1 John" :chapter 2}}]
   [{:start {:book "Numbers" :chapter 33}} {:start {:verse 1 :book "Psalms" :chapter 78} :end {:verse 37 :book "Psalms" :chapter 78}} {:start {:book "Isaiah" :chapter 25}} {:start {:book "1 John" :chapter 3}}]
   [{:start {:book "Numbers" :chapter 34}} {:start {:verse 38 :book "Psalms" :chapter 78}} {:start {:book "Isaiah" :chapter 26}} {:start {:book "1 John" :chapter 4}}]
   [{:start {:book "Numbers" :chapter 35}} {:start {:book "Psalms" :chapter 79}} {:start {:book "Isaiah" :chapter 27}} {:start {:book "1 John" :chapter 5}}]
   [{:start {:book "Numbers" :chapter 36}} {:start {:book "Psalms" :chapter 80}} {:start {:book "Isaiah" :chapter 28}} {:start {:book "2 John" :chapter 1}}]
   [{:start {:book "Deuteronomy" :chapter 1}} {:start {:book "Psalms" :chapter 81} :end {:book "Psalms" :chapter 82}} {:start {:book "Isaiah" :chapter 29}} 3 {:start {:book "John" :chapter 1}}]
   [{:start {:book "Deuteronomy" :chapter 2}} {:start {:book "Psalms" :chapter 83} :end {:book "Psalms" :chapter 84}} {:start {:book "Isaiah" :chapter 30}} {:start {:book "Jude" :chapter 1}}]
   [{:start {:book "Deuteronomy" :chapter 3}} {:start {:book "Psalms" :chapter 85}} {:start {:book "Isaiah" :chapter 31}} {:start {:book "Revelation" :chapter 1}}]
   [{:start {:book "Deuteronomy" :chapter 4}} {:start {:book "Psalms" :chapter 86} :end {:book "Psalms" :chapter 87}} {:start {:book "Isaiah" :chapter 32}} {:start {:book "Revelation" :chapter 2}}]
   [{:start {:book "Deuteronomy" :chapter 5}} {:start {:book "Psalms" :chapter 88}} {:start {:book "Isaiah" :chapter 33}} {:start {:book "Revelation" :chapter 3}}]
   [{:start {:book "Deuteronomy" :chapter 6}} {:start {:book "Psalms" :chapter 89}} {:start {:book "Isaiah" :chapter 34}} {:start {:book "Revelation" :chapter 4}}]
   [{:start {:book "Deuteronomy" :chapter 7}} {:start {:book "Psalms" :chapter 90}} {:start {:book "Isaiah" :chapter 35}} {:start {:book "Revelation" :chapter 5}}]
   [{:start {:book "Deuteronomy" :chapter 8}} {:start {:book "Psalms" :chapter 91}} {:start {:book "Isaiah" :chapter 36}} {:start {:book "Revelation" :chapter 6}}]
   [{:start {:book "Deuteronomy" :chapter 9}} {:start {:book "Psalms" :chapter 92} :end {:book "Psalms" :chapter 93}} {:start {:book "Isaiah" :chapter 37}} {:start {:book "Revelation" :chapter 7}}]
   [{:start {:book "Deuteronomy" :chapter 10}} {:start {:book "Psalms" :chapter 94}} {:start {:book "Isaiah" :chapter 38}} {:start {:book "Revelation" :chapter 8}}]
   [{:start {:book "Deuteronomy" :chapter 11}} {:start {:book "Psalms" :chapter 95} :end {:book "Psalms" :chapter 96}} {:start {:book "Isaiah" :chapter 39}} {:start {:book "Revelation" :chapter 9}}]
   [{:start {:book "Deuteronomy" :chapter 12}} {:start {:book "Psalms" :chapter 97} :end {:book "Psalms" :chapter 98}} {:start {:book "Isaiah" :chapter 40}} {:start {:book "Revelation" :chapter 10}}]
   [{:start {:book "Deuteronomy" :chapter 13} :end {:book "Deuteronomy" :chapter 14}} {:start {:book "Psalms" :chapter 99} :end {:book "Psalms" :chapter 101}} {:start {:book "Isaiah" :chapter 41}} {:start {:book "Revelation" :chapter 11}}]
   [{:start {:book "Deuteronomy" :chapter 15}} {:start {:book "Psalms" :chapter 102}} {:start {:book "Isaiah" :chapter 42}} {:start {:book "Revelation" :chapter 12}}]
   [{:start {:book "Deuteronomy" :chapter 16}} {:start {:book "Psalms" :chapter 103}} {:start {:book "Isaiah" :chapter 43}} {:start {:book "Revelation" :chapter 13}}]
   [{:start {:book "Deuteronomy" :chapter 17}} {:start {:book "Psalms" :chapter 104}} {:start {:book "Isaiah" :chapter 44}} {:start {:book "Revelation" :chapter 14}}]
   [{:start {:book "Deuteronomy" :chapter 18}} {:start {:book "Psalms" :chapter 105}} {:start {:book "Isaiah" :chapter 45}} {:start {:book "Revelation" :chapter 15}}]
   [{:start {:book "Deuteronomy" :chapter 19}} {:start {:book "Psalms" :chapter 106}} {:start {:book "Isaiah" :chapter 46}} {:start {:book "Revelation" :chapter 16}}]
   [{:start {:book "Deuteronomy" :chapter 20}} {:start {:book "Psalms" :chapter 107}} {:start {:book "Isaiah" :chapter 47}} {:start {:book "Revelation" :chapter 17}}]
   [{:start {:book "Deuteronomy" :chapter 21}} {:start {:book "Psalms" :chapter 108} :end {:book "Psalms" :chapter 109}} {:start {:book "Isaiah" :chapter 48}} {:start {:book "Revelation" :chapter 18}}]
   [{:start {:book "Deuteronomy" :chapter 22}} {:start {:book "Psalms" :chapter 110} :end {:book "Psalms" :chapter 111}} {:start {:book "Isaiah" :chapter 49}} {:start {:book "Revelation" :chapter 19}}]
   [{:start {:book "Deuteronomy" :chapter 23}} {:start {:book "Psalms" :chapter 112} :end {:book "Psalms" :chapter 113}} {:start {:book "Isaiah" :chapter 50}} {:start {:book "Revelation" :chapter 20}}]
   [{:start {:book "Deuteronomy" :chapter 24}} {:start {:book "Psalms" :chapter 114} :end {:book "Psalms" :chapter 115}} {:start {:book "Isaiah" :chapter 51}} {:start {:book "Revelation" :chapter 21}}]
   [{:start {:book "Deuteronomy" :chapter 25}} {:start {:book "Psalms" :chapter 116}} {:start {:book "Isaiah" :chapter 52}} {:start {:book "Revelation" :chapter 22}}]
   [{:start {:book "Deuteronomy" :chapter 26}} {:start {:book "Psalms" :chapter 117} :end {:book "Psalms" :chapter 118}} {:start {:book "Isaiah" :chapter 53}} {:start {:book "Matthew" :chapter 1}}]
   [{:start {:book "Deuteronomy" :chapter 27} :end {:verse 19 :book "Deuteronomy" :chapter 28}} {:start {:verse 1 :book "Psalms" :chapter 119} :end {:verse 24 :book "Psalms" :chapter 119}} {:start {:book "Isaiah" :chapter 54}} {:start {:book "Matthew" :chapter 2}}]
   [{:start {:verse 20 :book "Deuteronomy" :chapter 28}} {:start {:verse 25 :book "Psalms" :chapter 119} :end {:verse 48 :book "Psalms" :chapter 119}} {:start {:book "Isaiah" :chapter 55}} {:start {:book "Matthew" :chapter 3}}]
   [{:start {:book "Deuteronomy" :chapter 29}} {:start {:verse 49 :book "Psalms" :chapter 119} :end {:verse 72 :book "Psalms" :chapter 119}} {:start {:book "Isaiah" :chapter 56}} {:start {:book "Matthew" :chapter 4}}]
   [{:start {:book "Deuteronomy" :chapter 30}} {:start {:verse 73 :book "Psalms" :chapter 119} :end {:verse 96 :book "Psalms" :chapter 119}} {:start {:book "Isaiah" :chapter 57}} {:start {:book "Matthew" :chapter 5}}]
   [{:start {:book "Deuteronomy" :chapter 31}} {:start {:verse 97 :book "Psalms" :chapter 119} :end {:verse 120 :book "Psalms" :chapter 119}} {:start {:book "Isaiah" :chapter 58}} {:start {:book "Matthew" :chapter 6}}]
   [{:start {:book "Deuteronomy" :chapter 32}} {:start {:verse 121 :book "Psalms" :chapter 119} :end {:verse 144 :book "Psalms" :chapter 119}} {:start {:book "Isaiah" :chapter 59}} {:start {:book "Matthew" :chapter 7}}]
   [{:start {:book "Deuteronomy" :chapter 33} :end {:book "Deuteronomy" :chapter 34}} {:start {:verse 145 :book "Psalms" :chapter 119} :end {:verse 176 :book "Psalms" :chapter 119}} {:start {:book "Isaiah" :chapter 60}} {:start {:book "Matthew" :chapter 8}}]
   [{:start {:book "Joshua" :chapter 1}} {:start {:book "Psalms" :chapter 120} :end {:book "Psalms" :chapter 122}} {:start {:book "Isaiah" :chapter 61}} {:start {:book "Matthew" :chapter 9}}]
   [{:start {:book "Joshua" :chapter 2}} {:start {:book "Psalms" :chapter 123} :end {:book "Psalms" :chapter 125}} {:start {:book "Isaiah" :chapter 62}} {:start {:book "Matthew" :chapter 10}}]
   [{:start {:book "Joshua" :chapter 3}} {:start {:book "Psalms" :chapter 126} :end {:book "Psalms" :chapter 128}} {:start {:book "Isaiah" :chapter 63}} {:start {:book "Matthew" :chapter 11}}]
   [{:start {:book "Joshua" :chapter 4}} {:start {:book "Psalms" :chapter 129} :end {:book "Psalms" :chapter 131}} {:start {:book "Isaiah" :chapter 64}} {:start {:book "Matthew" :chapter 12}}]
   [{:start {:verse 5 :book "Joshua" :chapter 5} :end {:verse 5 :book "Joshua" :chapter 6}} {:start {:book "Psalms" :chapter 132} :end {:book "Psalms" :chapter 134}} {:start {:book "Isaiah" :chapter 65}} {:start {:book "Matthew" :chapter 13}}]
   [{:start {:verse 6 :book "Joshua" :chapter 6}} {:start {:book "Psalms" :chapter 135} :end {:book "Psalms" :chapter 136}} {:start {:book "Isaiah" :chapter 66}} {:start {:book "Matthew" :chapter 14}}]
   [{:start {:book "Joshua" :chapter 7}} {:start {:book "Psalms" :chapter 137} :end {:book "Psalms" :chapter 138}} {:start {:book "Jeremiah" :chapter 1}} {:start {:book "Matthew" :chapter 15}}]
   [{:start {:book "Joshua" :chapter 8}} {:start {:book "Psalms" :chapter 139}} {:start {:book "Jeremiah" :chapter 2}} {:start {:book "Matthew" :chapter 16}}]
   [{:start {:book "Joshua" :chapter 9}} {:start {:book "Psalms" :chapter 140} :end {:book "Psalms" :chapter 141}} {:start {:book "Jeremiah" :chapter 3}} {:start {:book "Matthew" :chapter 17}}]
   [{:start {:book "Joshua" :chapter 10}} {:start {:book "Psalms" :chapter 142} :end {:book "Psalms" :chapter 143}} {:start {:book "Jeremiah" :chapter 4}} {:start {:book "Matthew" :chapter 18}}]
   [{:start {:book "Joshua" :chapter 11}} {:start {:book "Psalms" :chapter 144}} {:start {:book "Jeremiah" :chapter 5}} {:start {:book "Matthew" :chapter 19}}]
   [{:start {:book "Joshua" :chapter 12} :end {:book "Joshua" :chapter 13}} {:start {:book "Psalms" :chapter 145}} {:start {:book "Jeremiah" :chapter 6}} {:start {:book "Matthew" :chapter 20}}]
   [{:start {:book "Joshua" :chapter 14} :end {:book "Joshua" :chapter 15}} {:start {:book "Psalms" :chapter 146} :end {:book "Psalms" :chapter 147}} {:start {:book "Jeremiah" :chapter 7}} {:start {:book "Matthew" :chapter 21}}]
   [{:start {:book "Joshua" :chapter 16} :end {:book "Joshua" :chapter 17}} {:start {:book "Psalms" :chapter 148}} {:start {:book "Jeremiah" :chapter 8}} {:start {:book "Matthew" :chapter 22}}]
   [{:start {:book "Joshua" :chapter 18} :end {:book "Joshua" :chapter 19}} {:start {:book "Psalms" :chapter 149} :end {:book "Psalms" :chapter 150}} {:start {:book "Jeremiah" :chapter 9}} {:start {:book "Matthew" :chapter 23}}]
   [{:start {:book "Joshua" :chapter 20} :end {:book "Joshua" :chapter 21}} {:start {:book "Acts" :chapter 1}} {:start {:book "Jeremiah" :chapter 10}} {:start {:book "Matthew" :chapter 24}}]
   [{:start {:book "Joshua" :chapter 22}} {:start {:book "Acts" :chapter 2}} {:start {:book "Jeremiah" :chapter 11}} {:start {:book "Matthew" :chapter 25}}]
   [{:start {:book "Joshua" :chapter 23}} {:start {:book "Acts" :chapter 3}} {:start {:book "Jeremiah" :chapter 12}} {:start {:book "Matthew" :chapter 26}}]
   [{:start {:book "Joshua" :chapter 24}} {:start {:book "Acts" :chapter 4}} {:start {:book "Jeremiah" :chapter 13}} {:start {:book "Matthew" :chapter 27}}]
   [{:start {:book "Judges" :chapter 1}} {:start {:book "Acts" :chapter 5}} {:start {:book "Jeremiah" :chapter 14}} {:start {:book "Matthew" :chapter 28}}]
   [{:start {:book "Judges" :chapter 2}} {:start {:book "Acts" :chapter 6}} {:start {:book "Jeremiah" :chapter 15}} {:start {:book "Mark" :chapter 1}}]
   [{:start {:book "Judges" :chapter 3}} {:start {:book "Acts" :chapter 7}} {:start {:book "Jeremiah" :chapter 16}} {:start {:book "Mark" :chapter 2}}]
   [{:start {:book "Judges" :chapter 4}} {:start {:book "Acts" :chapter 8}} {:start {:book "Jeremiah" :chapter 17}} {:start {:book "Mark" :chapter 3}}]
   [{:start {:book "Judges" :chapter 5}} {:start {:book "Acts" :chapter 9}} {:start {:book "Jeremiah" :chapter 18}} {:start {:book "Mark" :chapter 4}}]
   [{:start {:book "Judges" :chapter 6}} {:start {:book "Acts" :chapter 10}} {:start {:book "Jeremiah" :chapter 19}} {:start {:book "Mark" :chapter 5}}]
   [{:start {:book "Judges" :chapter 7}} {:start {:book "Acts" :chapter 11}} {:start {:book "Jeremiah" :chapter 20}} {:start {:book "Mark" :chapter 6}}]
   [{:start {:book "Judges" :chapter 8}} {:start {:book "Acts" :chapter 12}} {:start {:book "Jeremiah" :chapter 21}} {:start {:book "Mark" :chapter 7}}]
   [{:start {:book "Judges" :chapter 9}} {:start {:book "Acts" :chapter 13}} {:start {:book "Jeremiah" :chapter 22}} {:start {:book "Mark" :chapter 8}}]
   [{:start {:book "Judges" :chapter 10} :end {:verse 11 :book "Judges" :chapter 11}} {:start {:book "Acts" :chapter 14}} {:start {:book "Jeremiah" :chapter 23}} {:start {:book "Mark" :chapter 9}}]
   [{:start {:verse 12 :book "Judges" :chapter 11}} {:start {:book "Acts" :chapter 15}} {:start {:book "Jeremiah" :chapter 24}} {:start {:book "Mark" :chapter 10}}]
   [{:start {:book "Judges" :chapter 12}} {:start {:book "Acts" :chapter 16}} {:start {:book "Jeremiah" :chapter 25}} {:start {:book "Mark" :chapter 11}}]
   [{:start {:book "Judges" :chapter 13}} {:start {:book "Acts" :chapter 17}} {:start {:book "Jeremiah" :chapter 26}} {:start {:book "Mark" :chapter 12}}]
   [{:start {:book "Judges" :chapter 14}} {:start {:book "Acts" :chapter 18}} {:start {:book "Jeremiah" :chapter 27}} {:start {:book "Mark" :chapter 13}}]
   [{:start {:book "Judges" :chapter 15}} {:start {:book "Acts" :chapter 19}} {:start {:book "Jeremiah" :chapter 28}} {:start {:book "Mark" :chapter 14}}]
   [{:start {:book "Judges" :chapter 16}} {:start {:book "Acts" :chapter 20}} {:start {:book "Jeremiah" :chapter 29}} {:start {:book "Mark" :chapter 15}}]
   [{:start {:book "Judges" :chapter 17}} {:start {:book "Acts" :chapter 21}} {:start {:book "Jeremiah" :chapter 30} :end {:book "Jeremiah" :chapter 31}} {:start {:book "Mark" :chapter 16}}]
   [{:start {:book "Judges" :chapter 18}} {:start {:book "Acts" :chapter 22}} {:start {:book "Jeremiah" :chapter 32}} {:start {:book "Psalms" :chapter 1} :end {:book "Psalms" :chapter 2}}]
   [{:start {:book "Judges" :chapter 19}} {:start {:book "Acts" :chapter 23}} {:start {:book "Jeremiah" :chapter 33}} {:start {:book "Psalms" :chapter 3} :end {:book "Psalms" :chapter 4}}]
   [{:start {:book "Judges" :chapter 20}} {:start {:book "Acts" :chapter 24}} {:start {:book "Jeremiah" :chapter 34}} {:start {:book "Psalms" :chapter 5} :end {:book "Psalms" :chapter 6}}]
   [{:start {:book "Judges" :chapter 21}} {:start {:book "Acts" :chapter 25}} {:start {:book "Jeremiah" :chapter 35}} {:start {:book "Psalms" :chapter 7} :end {:book "Psalms" :chapter 8}}]
   [{:start {:book "Ruth" :chapter 1}} {:start {:book "Acts" :chapter 26}} {:start {:book "Jeremiah" :chapter 36}} {:start {:book "Jeremiah" :chapter 45}} {:start {:book "Psalms" :chapter 9}}]
   [{:start {:book "Ruth" :chapter 2}} {:start {:book "Acts" :chapter 27}} {:start {:book "Jeremiah" :chapter 37}} {:start {:book "Psalms" :chapter 10}}]
   [{:start {:book "Ruth" :chapter 3} :end {:book "Ruth" :chapter 4}} {:start {:book "Acts" :chapter 28}} {:start {:book "Jeremiah" :chapter 38}} {:start {:book "Psalms" :chapter 11} :end {:book "Psalms" :chapter 12}}]
   [{:start {:book "1 Samuel" :chapter 1}} {:start {:book "Romans" :chapter 1}} {:start {:book "Jeremiah" :chapter 39}} {:start {:book "Psalms" :chapter 13} :end {:book "Psalms" :chapter 14}}]
   [{:start {:book "1 Samuel" :chapter 2}} {:start {:book "Romans" :chapter 2}} {:start {:book "Jeremiah" :chapter 40}} {:start {:book "Psalms" :chapter 15} :end {:book "Psalms" :chapter 16}}]
   [{:start {:book "1 Samuel" :chapter 3}} {:start {:book "Romans" :chapter 3}} {:start {:book "Jeremiah" :chapter 41}} {:start {:book "Psalms" :chapter 17}}]
   [{:start {:book "1 Samuel" :chapter 4}} {:start {:book "Romans" :chapter 4}} {:start {:book "Jeremiah" :chapter 42}} {:start {:book "Psalms" :chapter 18}}]
   [{:start {:book "1 Samuel" :chapter 5} :end {:book "1 Samuel" :chapter 6}} {:start {:book "Romans" :chapter 5}} {:start {:book "Jeremiah" :chapter 43}} {:start {:book "Psalms" :chapter 19}}]
   [{:start {:book "1 Samuel" :chapter 7} :end {:book "1 Samuel" :chapter 8}} {:start {:book "Romans" :chapter 6}} {:start {:book "Jeremiah" :chapter 44}} {:start {:book "Psalms" :chapter 20} :end {:book "Psalms" :chapter 21}}]
   [{:start {:book "1 Samuel" :chapter 9}} {:start {:book "Romans" :chapter 7}} {:start {:book "Jeremiah" :chapter 46}} {:start {:book "Psalms" :chapter 22}}]
   [{:start {:book "1 Samuel" :chapter 10}} {:start {:book "Romans" :chapter 8}} {:start {:book "Jeremiah" :chapter 47}} {:start {:book "Psalms" :chapter 23} :end {:book "Psalms" :chapter 24}}]
   [{:start {:book "1 Samuel" :chapter 11}} {:start {:book "Romans" :chapter 9}} {:start {:book "Jeremiah" :chapter 48}} {:start {:book "Psalms" :chapter 25}}]
   [{:start {:book "1 Samuel" :chapter 12}} {:start {:book "Romans" :chapter 10}} {:start {:book "Jeremiah" :chapter 49}} {:start {:book "Psalms" :chapter 26} :end {:book "Psalms" :chapter 27}}]
   [{:start {:book "1 Samuel" :chapter 13}} {:start {:book "Romans" :chapter 11}} {:start {:book "Jeremiah" :chapter 50}} {:start {:book "Psalms" :chapter 28} :end {:book "Psalms" :chapter 29}}]
   [{:start {:book "1 Samuel" :chapter 14}} {:start {:book "Romans" :chapter 12}} {:start {:book "Jeremiah" :chapter 51}} {:start {:book "Psalms" :chapter 30}}]
   [{:start {:book "1 Samuel" :chapter 15}} {:start {:book "Romans" :chapter 13}} {:start {:book "Jeremiah" :chapter 52}} {:start {:book "Psalms" :chapter 31}}]
   [{:start {:book "1 Samuel" :chapter 16}} {:start {:book "Romans" :chapter 14}} {:start {:book "Lamentations" :chapter 1}} {:start {:book "Psalms" :chapter 32}}]
   [{:start {:book "1 Samuel" :chapter 17}} {:start {:book "Romans" :chapter 15}} {:start {:book "Lamentations" :chapter 2}} {:start {:book "Psalms" :chapter 33}}]
   [{:start {:book "1 Samuel" :chapter 18}} {:start {:book "Romans" :chapter 16}} {:start {:book "Lamentations" :chapter 3}} {:start {:book "Psalms" :chapter 34}}]
   [{:start {:book "1 Samuel" :chapter 19}} {:start {:book "1 Corinthians" :chapter 1}} {:start {:book "Lamentations" :chapter 4}} {:start {:book "Psalms" :chapter 35}}]
   [{:start {:book "1 Samuel" :chapter 20}} {:start {:book "1 Corinthians" :chapter 2}} {:start {:book "Lamentations" :chapter 5}} {:start {:book "Psalms" :chapter 36}}]
   [{:start {:book "1 Samuel" :chapter 21} :end {:book "1 Samuel" :chapter 22}} {:start {:book "1 Corinthians" :chapter 3}} {:start {:book "Ezekiel" :chapter 1}} {:start {:book "Psalms" :chapter 37}}]
   [{:start {:book "1 Samuel" :chapter 23}} {:start {:book "1 Corinthians" :chapter 4}} {:start {:book "Ezekiel" :chapter 2}} {:start {:book "Psalms" :chapter 38}}]
   [{:start {:book "1 Samuel" :chapter 24}} {:start {:book "1 Corinthians" :chapter 5}} {:start {:book "Ezekiel" :chapter 3}} {:start {:book "Psalms" :chapter 39}}]
   [{:start {:book "1 Samuel" :chapter 25}} {:start {:book "1 Corinthians" :chapter 6}} {:start {:book "Ezekiel" :chapter 4}} {:start {:book "Psalms" :chapter 40} :end {:book "Psalms" :chapter 41}}]
   [{:start {:book "1 Samuel" :chapter 26}} {:start {:book "1 Corinthians" :chapter 7}} {:start {:book "Ezekiel" :chapter 5}} {:start {:book "Psalms" :chapter 42} :end {:book "Psalms" :chapter 43}}]
   [{:start {:book "1 Samuel" :chapter 27}} {:start {:book "1 Corinthians" :chapter 8}} {:start {:book "Ezekiel" :chapter 6}} {:start {:book "Psalms" :chapter 44}}]
   [{:start {:book "1 Samuel" :chapter 28}} {:start {:book "1 Corinthians" :chapter 9}} {:start {:book "Ezekiel" :chapter 7}} {:start {:book "Psalms" :chapter 45}}]
   [{:start {:book "1 Samuel" :chapter 29} :end {:book "1 Samuel" :chapter 30}} {:start {:book "1 Corinthians" :chapter 10}} {:start {:book "Ezekiel" :chapter 8}} {:start {:book "Psalms" :chapter 46} :end {:book "Psalms" :chapter 47}}]
   [{:start {:book "1 Samuel" :chapter 31}} {:start {:book "1 Corinthians" :chapter 11}} {:start {:book "Ezekiel" :chapter 9}} {:start {:book "Psalms" :chapter 48}}]
   [{:start {:book "2 Samuel" :chapter 1}} {:start {:book "1 Corinthians" :chapter 12}} {:start {:book "Ezekiel" :chapter 10}} {:start {:book "Psalms" :chapter 49}}]
   [{:start {:book "2 Samuel" :chapter 2}} {:start {:book "1 Corinthians" :chapter 13}} {:start {:book "Ezekiel" :chapter 11}} {:start {:book "Psalms" :chapter 50}}]
   [{:start {:book "2 Samuel" :chapter 3}} {:start {:book "1 Corinthians" :chapter 14}} {:start {:book "Ezekiel" :chapter 12}} {:start {:book "Psalms" :chapter 51}}]
   [{:start {:book "2 Samuel" :chapter 4} :end {:book "2 Samuel" :chapter 5}} {:start {:book "1 Corinthians" :chapter 15}} {:start {:book "Ezekiel" :chapter 13}} {:start {:book "Psalms" :chapter 52} :end {:book "Psalms" :chapter 54}}]
   [{:start {:book "2 Samuel" :chapter 6}} {:start {:book "1 Corinthians" :chapter 16}} {:start {:book "Ezekiel" :chapter 14}} {:start {:book "Psalms" :chapter 55}}]
   [{:start {:book "2 Samuel" :chapter 7}} {:start {:book "2 Corinthians" :chapter 1}} {:start {:book "Ezekiel" :chapter 15}} {:start {:book "Psalms" :chapter 56} :end {:book "Psalms" :chapter 57}}]
   [{:start {:book "2 Samuel" :chapter 8} :end {:book "2 Samuel" :chapter 9}} {:start {:book "2 Corinthians" :chapter 2}} {:start {:book "Ezekiel" :chapter 16}} {:start {:book "Psalms" :chapter 58} :end {:book "Psalms" :chapter 59}}]
   [{:start {:book "2 Samuel" :chapter 10}} {:start {:book "2 Corinthians" :chapter 3}} {:start {:book "Ezekiel" :chapter 17}} {:start {:book "Psalms" :chapter 60} :end {:book "Psalms" :chapter 61}}]
   [{:start {:book "2 Samuel" :chapter 11}} {:start {:book "2 Corinthians" :chapter 4}} {:start {:book "Ezekiel" :chapter 18}} {:start {:book "Psalms" :chapter 62} :end {:book "Psalms" :chapter 63}}]
   [{:start {:book "2 Samuel" :chapter 12}} {:start {:book "2 Corinthians" :chapter 5}} {:start {:book "Ezekiel" :chapter 19}} {:start {:book "Psalms" :chapter 64} :end {:book "Psalms" :chapter 65}}]
   [{:start {:book "2 Samuel" :chapter 13}} {:start {:book "2 Corinthians" :chapter 6}} {:start {:book "Ezekiel" :chapter 20}} {:start {:book "Psalms" :chapter 66} :end {:book "Psalms" :chapter 67}}]
   [{:start {:book "2 Samuel" :chapter 14}} {:start {:book "2 Corinthians" :chapter 7}} {:start {:book "Ezekiel" :chapter 21}} {:start {:book "Psalms" :chapter 68}}]
   [{:start {:book "2 Samuel" :chapter 15}} {:start {:book "2 Corinthians" :chapter 8}} {:start {:book "Ezekiel" :chapter 22}} {:start {:book "Psalms" :chapter 69}}]
   [{:start {:book "2 Samuel" :chapter 16}} {:start {:book "2 Corinthians" :chapter 9}} {:start {:book "Ezekiel" :chapter 23}} {:start {:book "Psalms" :chapter 70} :end {:book "Psalms" :chapter 71}}]
   [{:start {:book "2 Samuel" :chapter 17}} {:start {:book "2 Corinthians" :chapter 10}} {:start {:book "Ezekiel" :chapter 24}} {:start {:book "Psalms" :chapter 72}}]
   [{:start {:book "2 Samuel" :chapter 18}} {:start {:book "2 Corinthians" :chapter 11}} {:start {:book "Ezekiel" :chapter 25}} {:start {:book "Psalms" :chapter 73}}]
   [{:start {:book "2 Samuel" :chapter 19}} {:start {:book "2 Corinthians" :chapter 12}} {:start {:book "Ezekiel" :chapter 26}} {:start {:book "Psalms" :chapter 74}}]
   [{:start {:book "2 Samuel" :chapter 20}} {:start {:book "2 Corinthians" :chapter 13}} {:start {:book "Ezekiel" :chapter 27}} {:start {:book "Psalms" :chapter 75} :end {:book "Psalms" :chapter 76}}]
   [{:start {:book "2 Samuel" :chapter 21}} {:start {:book "Galatians" :chapter 1}} {:start {:book "Ezekiel" :chapter 28}} {:start {:book "Psalms" :chapter 77}}]
   [{:start {:book "2 Samuel" :chapter 22}} {:start {:book "Galatians" :chapter 2}} {:start {:book "Ezekiel" :chapter 29}} {:start {:verse 1 :book "Psalms" :chapter 78} :end {:verse 37 :book "Psalms" :chapter 78}}]
   [{:start {:book "2 Samuel" :chapter 23}} {:start {:book "Galatians" :chapter 3}} {:start {:book "Ezekiel" :chapter 30}} {:start {:verse 38 :book "Psalms" :chapter 78}}]
   [{:start {:book "2 Samuel" :chapter 24}} {:start {:book "Galatians" :chapter 4}} {:start {:book "Ezekiel" :chapter 31}} {:start {:book "Psalms" :chapter 79}}]
   [{:start {:book "1 Kings" :chapter 1}} {:start {:book "Galatians" :chapter 5}} {:start {:book "Ezekiel" :chapter 32}} {:start {:book "Psalms" :chapter 80}}]
   [{:start {:book "1 Kings" :chapter 2}} {:start {:book "Galatians" :chapter 6}} {:start {:book "Ezekiel" :chapter 33}} {:start {:book "Psalms" :chapter 81} :end {:book "Psalms" :chapter 82}}]
   [{:start {:book "1 Kings" :chapter 3}} {:start {:book "Ephesians" :chapter 1}} {:start {:book "Ezekiel" :chapter 34}} {:start {:book "Psalms" :chapter 83} :end {:book "Psalms" :chapter 84}}]
   [{:start {:book "1 Kings" :chapter 4} :end {:book "1 Kings" :chapter 5}} {:start {:book "Ephesians" :chapter 2}} {:start {:book "Ezekiel" :chapter 35}} {:start {:book "Psalms" :chapter 85}}]
   [{:start {:book "1 Kings" :chapter 6}} {:start {:book "Ephesians" :chapter 3}} {:start {:book "Ezekiel" :chapter 36}} {:start {:book "Psalms" :chapter 86}}]
   [{:start {:book "1 Kings" :chapter 7}} {:start {:book "Ephesians" :chapter 4}} {:start {:book "Ezekiel" :chapter 37}} {:start {:book "Psalms" :chapter 87} :end {:book "Psalms" :chapter 88}}]
   [{:start {:book "1 Kings" :chapter 8}} {:start {:book "Ephesians" :chapter 5}} {:start {:book "Ezekiel" :chapter 38}} {:start {:book "Psalms" :chapter 89}}]
   [{:start {:book "1 Kings" :chapter 9}} {:start {:book "Ephesians" :chapter 6}} {:start {:book "Ezekiel" :chapter 39}} {:start {:book "Psalms" :chapter 90}}]
   [{:start {:book "1 Kings" :chapter 10}} {:start {:book "Philippians" :chapter 1}} {:start {:book "Ezekiel" :chapter 40}} {:start {:book "Psalms" :chapter 91}}]
   [{:start {:book "1 Kings" :chapter 11}} {:start {:book "Philippians" :chapter 2}} {:start {:book "Ezekiel" :chapter 41}} {:start {:book "Psalms" :chapter 92} :end {:book "Psalms" :chapter 93}}]
   [{:start {:book "1 Kings" :chapter 12}} {:start {:book "Philippians" :chapter 3}} {:start {:book "Ezekiel" :chapter 42}} {:start {:book "Psalms" :chapter 94}}]
   [{:start {:book "1 Kings" :chapter 13}} {:start {:book "Philippians" :chapter 4}} {:start {:book "Ezekiel" :chapter 43}} {:start {:book "Psalms" :chapter 95} :end {:book "Psalms" :chapter 96}}]
   [{:start {:book "1 Kings" :chapter 14}} {:start {:book "Colossians" :chapter 1}} {:start {:book "Ezekiel" :chapter 44}} {:start {:book "Psalms" :chapter 97} :end {:book "Psalms" :chapter 98}}]
   [{:start {:book "1 Kings" :chapter 15}} {:start {:book "Colossians" :chapter 2}} {:start {:book "Ezekiel" :chapter 45}} {:start {:book "Psalms" :chapter 99} :end {:book "Psalms" :chapter 101}}]
   [{:start {:book "1 Kings" :chapter 16}} {:start {:book "Colossians" :chapter 3}} {:start {:book "Ezekiel" :chapter 46}} {:start {:book "Psalms" :chapter 102}}]
   [{:start {:book "1 Kings" :chapter 17}} {:start {:book "Colossians" :chapter 4}} {:start {:book "Ezekiel" :chapter 47}} {:start {:book "Psalms" :chapter 103}}]
   [{:start {:book "1 Kings" :chapter 18}} {:start {:book "1 Thessalonians" :chapter 1}} {:start {:book "Ezekiel" :chapter 48}} {:start {:book "Psalms" :chapter 104}}]
   [{:start {:book "1 Kings" :chapter 19}} {:start {:book "1 Thessalonians" :chapter 2}} {:start {:book "Daniel" :chapter 1}} {:start {:book "Psalms" :chapter 105}}]
   [{:start {:book "1 Kings" :chapter 20}} {:start {:book "1 Thessalonians" :chapter 3}} {:start {:book "Daniel" :chapter 2}} {:start {:book "Psalms" :chapter 106}}]
   [{:start {:book "1 Kings" :chapter 21}} {:start {:book "1 Thessalonians" :chapter 4}} {:start {:book "Daniel" :chapter 3}} {:start {:book "Psalms" :chapter 107}}]
   [{:start {:book "1 Kings" :chapter 22}} {:start {:book "1 Thessalonians" :chapter 5}} {:start {:book "Daniel" :chapter 4}} {:start {:book "Psalms" :chapter 108} :end {:book "Psalms" :chapter 109}}]
   [{:start {:book "2 Kings" :chapter 1}} {:start {:book "2 Thessalonians" :chapter 1}} {:start {:book "Daniel" :chapter 5}} {:start {:book "Psalms" :chapter 110} :end {:book "Psalms" :chapter 111}}]
   [{:start {:book "2 Kings" :chapter 2}} {:start {:book "2 Thessalonians" :chapter 2}} {:start {:book "Daniel" :chapter 6}} {:start {:book "Psalms" :chapter 112} :end {:book "Psalms" :chapter 113}}]
   [{:start {:book "2 Kings" :chapter 3}} {:start {:book "2 Thessalonians" :chapter 3}} {:start {:book "Daniel" :chapter 7}} {:start {:book "Psalms" :chapter 114} :end {:book "Psalms" :chapter 115}}]
   [{:start {:book "2 Kings" :chapter 4}} {:start {:book "1 Timothy" :chapter 1}} {:start {:book "Daniel" :chapter 8}} {:start {:book "Psalms" :chapter 116}}]
   [{:start {:book "2 Kings" :chapter 5}} {:start {:book "1 Timothy" :chapter 2}} {:start {:book "Daniel" :chapter 9}} {:start {:book "Psalms" :chapter 117} :end {:book "Psalms" :chapter 118}}]
   [{:start {:book "2 Kings" :chapter 6}} {:start {:book "1 Timothy" :chapter 3}} {:start {:book "Daniel" :chapter 10}} {:start {:verse 1 :book "Psalms" :chapter 119} :end {:verse 24 :book "Psalms" :chapter 119}}]
   [{:start {:book "2 Kings" :chapter 7}} {:start {:book "1 Timothy" :chapter 4}} {:start {:book "Daniel" :chapter 11}} {:start {:verse 25 :book "Psalms" :chapter 119} :end {:verse 48 :book "Psalms" :chapter 119}}]
   [{:start {:book "2 Kings" :chapter 8}} {:start {:book "1 Timothy" :chapter 5}} {:start {:book "Daniel" :chapter 12}} {:start {:verse 49 :book "Psalms" :chapter 119} :end {:verse 72 :book "Psalms" :chapter 119}}]
   [{:start {:book "2 Kings" :chapter 9}} {:start {:book "1 Timothy" :chapter 6}} {:start {:book "Hosea" :chapter 1}} {:start {:verse 73 :book "Psalms" :chapter 119} :end {:verse 96 :book "Psalms" :chapter 119}}]
   [{:start {:book "2 Kings" :chapter 10}} {:start {:book "2 Timothy" :chapter 1}} {:start {:book "Hosea" :chapter 2}} {:start {:verse 97 :book "Psalms" :chapter 119} :end {:verse 120 :book "Psalms" :chapter 119}}]
   [{:start {:book "2 Kings" :chapter 11} :end {:book "2 Kings" :chapter 12}} {:start {:book "2 Timothy" :chapter 2}} {:start {:book "Hosea" :chapter 3} :end {:book "Hosea" :chapter 4}} {:start {:verse 121 :book "Psalms" :chapter 119} :end {:verse 144 :book "Psalms" :chapter 119}}]
   [{:start {:book "2 Kings" :chapter 13}} {:start {:book "2 Timothy" :chapter 3}} {:start {:book "Hosea" :chapter 5} :end {:book "Hosea" :chapter 6}} {:start {:verse 145 :book "Psalms" :chapter 119} :end {:verse 176 :book "Psalms" :chapter 119}}]
   [{:start {:book "2 Kings" :chapter 14}} {:start {:book "2 Timothy" :chapter 4}} {:start {:book "Hosea" :chapter 7}} {:start {:book "Psalms" :chapter 120} :end {:book "Psalms" :chapter 122}}]
   [{:start {:book "2 Kings" :chapter 15}} {:start {:book "Titus" :chapter 1}} {:start {:book "Hosea" :chapter 8}} {:start {:book "Psalms" :chapter 123} :end {:book "Psalms" :chapter 125}}]
   [{:start {:book "2 Kings" :chapter 16}} {:start {:book "Titus" :chapter 2}} {:start {:book "Hosea" :chapter 9}} {:start {:book "Psalms" :chapter 126} :end {:book "Psalms" :chapter 128}}]
   [{:start {:book "2 Kings" :chapter 17}} {:start {:book "Titus" :chapter 3}} {:start {:book "Hosea" :chapter 10}} {:start {:book "Psalms" :chapter 129} :end {:book "Psalms" :chapter 131}}]
   [{:start {:book "2 Kings" :chapter 18}} {:start {:book "Philemon" :chapter 1}} {:start {:book "Hosea" :chapter 11}} {:start {:book "Psalms" :chapter 132} :end {:book "Psalms" :chapter 134}}]
   [{:start {:book "2 Kings" :chapter 19}} {:start {:book "Hebrews" :chapter 1}} {:start {:book "Hosea" :chapter 12}} {:start {:book "Psalms" :chapter 135} :end {:book "Psalms" :chapter 136}}]
   [{:start {:book "2 Kings" :chapter 20}} {:start {:book "Hebrews" :chapter 2}} {:start {:book "Hosea" :chapter 13}} {:start {:book "Psalms" :chapter 137} :end {:book "Psalms" :chapter 138}}]
   [{:start {:book "2 Kings" :chapter 21}} {:start {:book "Hebrews" :chapter 3}} {:start {:book "Hosea" :chapter 14}} {:start {:book "Psalms" :chapter 139}}]
   [{:start {:book "2 Kings" :chapter 22}} {:start {:book "Hebrews" :chapter 4}} {:start {:book "Joel" :chapter 1}} {:start {:book "Psalms" :chapter 140} :end {:book "Psalms" :chapter 141}}]
   [{:start {:book "2 Kings" :chapter 23}} {:start {:book "Hebrews" :chapter 5}} {:start {:book "Joel" :chapter 2}} {:start {:book "Psalms" :chapter 142}}]
   [{:start {:book "2 Kings" :chapter 24}} {:start {:book "Hebrews" :chapter 6}} {:start {:book "Joel" :chapter 3}} {:start {:book "Psalms" :chapter 143}}]
   [{:start {:book "2 Kings" :chapter 25}} {:start {:book "Hebrews" :chapter 7}} {:start {:book "Amos" :chapter 1}} {:start {:book "Psalms" :chapter 144}}]
   [{:start {:book "1 Chronicles" :chapter 1} :end {:book "1 Chronicles" :chapter 2}} {:start {:book "Hebrews" :chapter 8}} {:start {:book "Amos" :chapter 2}} {:start {:book "Psalms" :chapter 145}}]
   [{:start {:book "1 Chronicles" :chapter 3} :end {:book "1 Chronicles" :chapter 4}} {:start {:book "Hebrews" :chapter 9}} {:start {:book "Amos" :chapter 3}} {:start {:book "Psalms" :chapter 146} :end {:book "Psalms" :chapter 147}}]
   [{:start {:book "1 Chronicles" :chapter 5} :end {:book "1 Chronicles" :chapter 6}} {:start {:book "Hebrews" :chapter 10}} {:start {:book "Amos" :chapter 4}} {:start {:book "Psalms" :chapter 148} :end {:book "Psalms" :chapter 150}}]
   [{:start {:book "1 Chronicles" :chapter 7} :end {:book "1 Chronicles" :chapter 8}} {:start {:book "Hebrews" :chapter 11}} {:start {:book "Amos" :chapter 5}} {:start {:verse 1 :book "Luke" :chapter 1} :end {:verse 38 :book "Luke" :chapter 1}}]
   [{:start {:book "1 Chronicles" :chapter 9} :end {:book "1 Chronicles" :chapter 10}} {:start {:book "Hebrews" :chapter 12}} {:start {:book "Amos" :chapter 6}} {:start {:verse 39 :book "Luke" :chapter 1}}]
   [{:start {:book "1 Chronicles" :chapter 11} :end {:book "1 Chronicles" :chapter 12}} {:start {:book "Hebrews" :chapter 13}} {:start {:book "Amos" :chapter 7}} {:start {:book "Luke" :chapter 2}}]
   [{:start {:book "1 Chronicles" :chapter 13} :end {:book "1 Chronicles" :chapter 14}} {:start {:book "James" :chapter 1}} {:start {:book "Amos" :chapter 8}} {:start {:book "Luke" :chapter 3}}]
   [{:start {:book "1 Chronicles" :chapter 15}} {:start {:book "James" :chapter 2}} {:start {:book "Amos" :chapter 9}} {:start {:book "Luke" :chapter 4}}]
   [{:start {:book "1 Chronicles" :chapter 16}} {:start {:book "James" :chapter 3}} {:start {:book "Obadiah" :chapter 1}} {:start {:book "Luke" :chapter 5}}]
   [{:start {:book "1 Chronicles" :chapter 17}} {:start {:book "James" :chapter 4}} {:start {:book "Jonah" :chapter 1}} {:start {:book "Luke" :chapter 6}}]
   [{:start {:book "1 Chronicles" :chapter 18}} {:start {:book "James" :chapter 5}} {:start {:book "Jonah" :chapter 2}} {:start {:book "Luke" :chapter 7}}]
   [{:start {:book "1 Chronicles" :chapter 19} :end {:book "1 Chronicles" :chapter 20}} {:start {:book "1 Peter" :chapter 1}} {:start {:book "Jonah" :chapter 3}} {:start {:book "Luke" :chapter 8}}]
   [{:start {:book "1 Chronicles" :chapter 21}} {:start {:book "1 Peter" :chapter 2}} {:start {:book "Jonah" :chapter 4}} {:start {:book "Luke" :chapter 9}}]
   [{:start {:book "1 Chronicles" :chapter 22}} {:start {:book "1 Peter" :chapter 3}} {:start {:book "Micah" :chapter 1}} {:start {:book "Luke" :chapter 10}}]
   [{:start {:book "1 Chronicles" :chapter 23}} {:start {:book "1 Peter" :chapter 4}} {:start {:book "Micah" :chapter 2}} {:start {:book "Luke" :chapter 11}}]
   [{:start {:book "1 Chronicles" :chapter 24} :end {:book "1 Chronicles" :chapter 25}} {:start {:book "1 Peter" :chapter 5}} {:start {:book "Micah" :chapter 3}} {:start {:book "Luke" :chapter 12}}]
   [{:start {:book "1 Chronicles" :chapter 26} :end {:book "1 Chronicles" :chapter 27}} {:start {:book "2 Peter" :chapter 1}} {:start {:book "Micah" :chapter 4}} {:start {:book "Luke" :chapter 13}}]
   [{:start {:book "1 Chronicles" :chapter 28}} {:start {:book "2 Peter" :chapter 2}} {:start {:book "Micah" :chapter 5}} {:start {:book "Luke" :chapter 14}}]
   [{:start {:book "1 Chronicles" :chapter 29}} {:start {:book "2 Peter" :chapter 3}} {:start {:book "Micah" :chapter 6}} {:start {:book "Luke" :chapter 15}}]
   [{:start {:book "2 Chronicles" :chapter 1}} {:start {:book "1 John" :chapter 1}} {:start {:book "Micah" :chapter 7}} {:start {:book "Luke" :chapter 16}}]
   [{:start {:book "2 Chronicles" :chapter 2}} {:start {:book "1 John" :chapter 2}} {:start {:book "Nahum" :chapter 1}} {:start {:book "Luke" :chapter 17}}]
   [{:start {:book "2 Chronicles" :chapter 3} :end {:book "2 Chronicles" :chapter 4}} {:start {:book "1 John" :chapter 3}} {:start {:book "Nahum" :chapter 2}} {:start {:book "Luke" :chapter 18}}]
   [{:start {:book "2 Chronicles" :chapter 5} :end {:verse 11 :book "2 Chronicles" :chapter 6}} {:start {:book "1 John" :chapter 4}} {:start {:book "Nahum" :chapter 3}} {:start {:book "Luke" :chapter 19}}]
   [{:start {:verse 12 :book "2 Chronicles" :chapter 6}} {:start {:book "1 John" :chapter 5}} {:start {:book "Habakkuk" :chapter 1}} {:start {:book "Luke" :chapter 20}}]
   [{:start {:book "2 Chronicles" :chapter 7}} {:start {:book "2 John" :chapter 1}} {:start {:book "Habakkuk" :chapter 2}} {:start {:book "Luke" :chapter 21}}]
   [{:start {:book "2 Chronicles" :chapter 8}} {:start {:book "John" :chapter 1}} {:start {:book "Habakkuk" :chapter 3}} {:start {:book "Luke" :chapter 22}}]
   [{:start {:book "2 Chronicles" :chapter 9}} {:start {:book "Jude" :chapter 1}} {:start {:book "Zephaniah" :chapter 1}} {:start {:book "Luke" :chapter 23}}]
   [{:start {:book "2 Chronicles" :chapter 10}} {:start {:book "Revelation" :chapter 1}} {:start {:book "Zephaniah" :chapter 2}} {:start {:book "Luke" :chapter 24}}]
   [{:start {:book "2 Chronicles" :chapter 11} :end {:book "2 Chronicles" :chapter 12}} {:start {:book "Revelation" :chapter 2}} {:start {:book "Zephaniah" :chapter 3}} {:start {:book "John" :chapter 1}}]
   [{:start {:book "2 Chronicles" :chapter 13}} {:start {:book "Revelation" :chapter 3}} {:start {:book "Haggai" :chapter 1}} {:start {:book "John" :chapter 2}}]
   [{:start {:book "2 Chronicles" :chapter 14} :end {:book "2 Chronicles" :chapter 15}} {:start {:book "Revelation" :chapter 4}} {:start {:book "Haggai" :chapter 2}} {:start {:book "John" :chapter 3}}]
   [{:start {:book "2 Chronicles" :chapter 16}} {:start {:book "Revelation" :chapter 5}} {:start {:book "Zechariah" :chapter 1}} {:start {:book "John" :chapter 4}}]
   [{:start {:book "2 Chronicles" :chapter 17}} {:start {:book "Revelation" :chapter 6}} {:start {:book "Zechariah" :chapter 2}} {:start {:book "John" :chapter 5}}]
   [{:start {:book "2 Chronicles" :chapter 18}} {:start {:book "Revelation" :chapter 7}} {:start {:book "Zechariah" :chapter 3}} {:start {:book "John" :chapter 6}}]
   [{:start {:book "2 Chronicles" :chapter 19} :end {:book "2 Chronicles" :chapter 20}} {:start {:book "Revelation" :chapter 8}} {:start {:book "Zechariah" :chapter 4}} {:start {:book "John" :chapter 7}}]
   [{:start {:book "2 Chronicles" :chapter 21}} {:start {:book "Revelation" :chapter 9}} {:start {:book "Zechariah" :chapter 5}} {:start {:book "John" :chapter 8}}]
   [{:start {:book "2 Chronicles" :chapter 22} :end {:book "2 Chronicles" :chapter 23}} {:start {:book "Revelation" :chapter 10}} {:start {:book "Zechariah" :chapter 6}} {:start {:book "John" :chapter 9}}]
   [{:start {:book "2 Chronicles" :chapter 24}} {:start {:book "Revelation" :chapter 11}} {:start {:book "Zechariah" :chapter 7}} {:start {:book "John" :chapter 10}}]
   [{:start {:book "2 Chronicles" :chapter 25}} {:start {:book "Revelation" :chapter 12}} {:start {:book "Zechariah" :chapter 8}} {:start {:book "John" :chapter 11}}]
   [{:start {:book "2 Chronicles" :chapter 26}} {:start {:book "Revelation" :chapter 13}} {:start {:book "Zechariah" :chapter 9}} {:start {:book "John" :chapter 12}}]
   [{:start {:book "2 Chronicles" :chapter 27} :end {:book "2 Chronicles" :chapter 28}} {:start {:book "Revelation" :chapter 14}} {:start {:book "Zechariah" :chapter 10}} {:start {:book "John" :chapter 13}}]
   [{:start {:book "2 Chronicles" :chapter 29}} {:start {:book "Revelation" :chapter 15}} {:start {:book "Zechariah" :chapter 11}} {:start {:book "John" :chapter 14}}]
   [{:start {:book "2 Chronicles" :chapter 30}} {:start {:book "Revelation" :chapter 16}} {:start {:book "Zechariah" :chapter 12} :end {:verse 1 :book "Zechariah" :chapter 13}} {:start {:book "John" :chapter 15}}]
   [{:start {:book "2 Chronicles" :chapter 31}} {:start {:book "Revelation" :chapter 17}} {:start {:verse 2 :book "Zechariah" :chapter 13}} {:start {:book "John" :chapter 16}}]
   [{:start {:book "2 Chronicles" :chapter 32}} {:start {:book "Revelation" :chapter 18}} {:start {:book "Zechariah" :chapter 14}} {:start {:book "John" :chapter 17}}]
   [{:start {:book "2 Chronicles" :chapter 33}} {:start {:book "Revelation" :chapter 19}} {:start {:book "Malachi" :chapter 1}} {:start {:book "John" :chapter 18}}]
   [{:start {:book "2 Chronicles" :chapter 34}} {:start {:book "Revelation" :chapter 20}} {:start {:book "Malachi" :chapter 2}} {:start {:book "John" :chapter 19}}]
   [{:start {:book "2 Chronicles" :chapter 35}} {:start {:book "Revelation" :chapter 21}} {:start {:book "Malachi" :chapter 3}} {:start {:book "John" :chapter 20}}]
   [{:start {:book "2 Chronicles" :chapter 36}} {:start {:book "Revelation" :chapter 22}} {:start {:book "Malachi" :chapter 4}} {:start {:book "John" :chapter 21}}]])
